apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: streamsets-pull-external-resources
  name: streamsets-pull-external-resources
  namespace: streamsetsdemos
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: streamsets-pull-external-resources
    spec:
      restartPolicy: OnFailure
      securityContext: {}
      imagePullSecrets: []
      containers:
        - name: pull-external-resources
          image: minio/mc:latest
          imagePullPolicy: IfNotPresent
          securityContext: {}
          workingDir: "/libsdir"
          command: ["sh","-ce","/scripts/sync-minio.sh"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: streamsets-libspull-credentials
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streamsets-libspull-credentials
                  key: secret_access_key
            - name: AWS_S3_ENDPOINT
              value: https://10.43.107.22:443
            - name: AWS_S3_BUCKET_NAME
              value: streamsets-datacollector-external-resources
            - name: AWS_S3_BUCKET_PATH_USER_LIBS
              value: "/user-libs"
            - name: AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS
              value: "/streamsets-libs-extras"
            - name: AWS_S3_BUCKET_PATH_RESOURCES
              value: "/resources"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: pull-script-minio
              mountPath: /scripts
            - mountPath: "/externalworkingdir"
              name: "externalworkingdir"
              readOnly: false
      volumes:
        - name: pull-script-minio
          configMap:
            name: streamsets-pull-external-resources-minio
            defaultMode: 0777
        - name: externalworkingdir
          persistentVolumeClaim:
            claimName: streamsets-external-resources
