apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: streamsets-jmxexporter-configs
  name: streamsets-jmxexporter-configs
  namespace: streamsetsdemos
data:
  config.yml: |-
    attrNameSnakeCase: true
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      - pattern: ".*"