apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamsets-deployment-<UUID>
    vendor: streamsets-sch
    env: na01
  name: streamsets-deployment-<UUID>
  namespace: streamsetsdemos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamsets-deployment-<UUID>
  template:
    metadata:
      labels:
        app: streamsets-deployment-<UUID>
        vendor: streamsets-sch
        env: na01
    spec:
      initContainers:
        - name: init-jmx-exporter
          image: bitnami/jmx-exporter:1.0.1
          imagePullPolicy: IfNotPresent
          securityContext: {}
          workingDir: /jmxexporter
          command: ["sh"]
          args:
            - -ce
            - |
              echo "Copying jmx_prometheus_javaagent"
              cp -a /opt/bitnami/jmx-exporter/jmx_prometheus_javaagent.jar /jmxexporter/
              echo "Copy Complete!"
          volumeMounts:
            - mountPath: /jmxexporter
              name: jmxexporter-shared
              readOnly: false
      containers:
        - env:
            - name: STREAMSETS_DEPLOYMENT_ID
              value: <UUID>:<ORGID>
            - name: STREAMSETS_DEPLOYMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: streamsets-deployment-secret-<UUID>
                  optional: false
            - name: STREAMSETS_DEPLOYMENT_SCH_URL
              value: https://na01.hub.streamsets.com
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /public-rest/ping
              port: engine-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: streamsets-engine-<UUID>
          ports:
            - containerPort: 18630
              name: engine-port
          resources:
            requests:
              memory: 1Gi
              cpu: "1"
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /public-rest/ping
              port: engine-port
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: jmxexporter-config
              mountPath: /jmxexporter_configs
              readOnly: true
            - name: jmxexporter-shared
              mountPath: /jmxexporter
              readOnly: true
      volumes:
        - name: jmxexporter-config
          configMap:
            name: streamsets-jmxexporter-configs
        - name: jmxexporter-shared
          emptyDir: {}
      dnsPolicy: Default
