attrNameSnakeCase: true
lowercaseOutputName: false
lowercaseOutputLabelNames: true
whitelistObjectNames:
 - java.lang:type=OperatingSystem
 - metrics:name=jvm.*
 - metrics:name=sdc.pipeline.*

rules:
  # pattern for pipeline COUNTER metrics
  - pattern: 'metrics<name=sdc\.pipeline\.([^\.]+)\.([^\.]+)\.pipeline\.([^\.]+)\.counter><>Count: (\d+)'
    name: sdc_pipeline_counter_$1_$2_$3
    value: $4
    labels:
      pipeline: $1
      pipeline_revision: $2
      category: pipeline
      metric: $3
    help: "StreamSets SDC Pipeline COUNTER Metric $1_$2_$3"
    cache: false
    type: COUNTER
    attrNameSnakeCase: false
  
  # pattern for pipeline METER metrics (multiple attributes)
  - pattern: 'metrics<name=sdc\.pipeline\.([^\.]+)\.([^\.]+)\.pipeline\.([^\.]+)\.meter><>(\w+): (.*)'
    name: sdc_pipeline_meter_$1_$2_$3_$4
    value: $5
    labels:
      pipeline: $1
      pipeline_revision: $2
      category: pipeline
      metric: $3
    help: "StreamSets SDC Pipeline METER Metric $1_$2_$3_$4"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # pattern for stage COUNTER metrics
  - pattern: 'metrics<name=sdc\.pipeline\.([^\.]+)\.([^\.]+)\.stage\.([^\.]+)\.([^\.]+)\.counter><>Count: (\d+)'
    name: sdc_pipeline_stage_counter_$1_$2_$3_$4
    value: $5
    labels:
      pipeline: $1
      pipeline_revision: $2
      category: stage
      stage: $3
      metric: $4
    help: "StreamSets SDC Pipeline Stage COUNTER Metric $3_$4 for pipeline $1_$2"
    cache: false
    type: COUNTER
    attrNameSnakeCase: false

  # pattern for stage METER metrics (multiple attributes)
  - pattern: 'metrics<name=sdc\.pipeline\.([^\.]+)\.([^\.]+)\.stage\.([^\.]+)\.([^\.]+)\.meter><>(\w+): (.*)'
    name: sdc_pipeline_stage_meter_$1_$2_$3_$4_$5
    value: $6
    labels:
      pipeline: $1
      pipeline_revision: $2
      category: stage
      stage: $3
      metric: $4
    help: "StreamSets SDC Pipeline Stage METER Metric $3_$4_$5 for pipeline $1_$2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # pattern for JVM metrics
  - pattern: 'metrics<name=^jvm\.(.+)$><>Value: (.*)'
    name: sdc_jvm_$1
    value: $2
    labels:
      category: jvm
    help: "StreamSets SDC JVM metric jvm.$1"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false