attrNameSnakeCase: true
lowercaseOutputName: false
lowercaseOutputLabelNames: true
whitelistObjectNames:
 - metrics:name=jvm.*
 - metrics:name=sdc.pipeline.*

rules:
  - pattern: "^metrics:name=sdc\.pipeline\.([a-zA-Z0-9_-]+)\.([a-zA-Z0-9_-]+)\.([a-zA-Z0-9_-]+)\.([a-zA-Z0-9_:-]+)\.([a-zA-Z0-9_:-]+)\.([a-zA-Z0-9_:-]+)$"
    name: $1
    labels:
      pipeline: $2
      revision: $3
      category: $4
      stage: $5
      metric: $6
    type: $7