apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: streamsets-pull-external-resources-minio
  name: streamsets-pull-external-resources-minio
  namespace: streamsetsdemos
data:
  sync-minio.sh: |-
    #!/bin/sh

    mc alias set myminio "${AWS_S3_ENDPOINT}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}" --insecure

    echo "Starting Sync for streamsets-libs-extras"
    mkdir -p /externalworkingdir${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS}
    mc mirror --remove --overwrite --retry --summary --insecure myminio/${AWS_S3_BUCKET_NAME}${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS} /externalworkingdir${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS}
    ls -al /externalworkingdir${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS}/
    echo "Sync complete - ststreamsets-libs-extras"

    echo "Starting Sync for user-libs"
    mkdir -p /externalworkingdir${AWS_S3_BUCKET_PATH_USER_LIBS}
    mc mirror --remove --overwrite --retry --summary --insecure myminio/${AWS_S3_BUCKET_NAME}${AWS_S3_BUCKET_PATH_USER_LIBS} /externalworkingdir${AWS_S3_BUCKET_PATH_USER_LIBS}
    ls -al /externalworkingdir${AWS_S3_BUCKET_PATH_USER_LIBS}/
    echo "Sync complete - user-libs"

    echo "Starting Sync for resources"
    mkdir -p /externalworkingdir${AWS_S3_BUCKET_PATH_RESOURCES}
    mc mirror --remove --overwrite --retry --summary --insecure myminio/${AWS_S3_BUCKET_NAME}${AWS_S3_BUCKET_PATH_RESOURCES} /externalworkingdir${AWS_S3_BUCKET_PATH_RESOURCES}
    ls -al /externalworkingdir${AWS_S3_BUCKET_PATH_RESOURCES}/
    echo "Sync complete - resources"