---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-external-resources
  namespace: streamsetsdemos
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 20G