apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: streamsets-pull-external-resources-aws
  name: streamsets-pull-external-resources-aws
  namespace: streamsetsdemos
data:
  sync-aws.sh: |-
    #!/bin/sh

    echo "Starting Sync for streamsets-libs-extras"
    mkdir -p /externalworkingdir${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS}
    aws s3 sync --delete s3://${AWS_S3_BUCKET_NAME}${AWS_S3_BUCKET_PREFIX}${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS} /externalworkingdir${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS}
    echo "Sync complete - ststreamsets-libs-extras"

    echo "Starting Sync for user-libs"
    mkdir -p /externalworkingdir${AWS_S3_BUCKET_PATH_USER_LIBS}
    aws s3 sync --delete s3://${AWS_S3_BUCKET_NAME}${AWS_S3_BUCKET_PREFIX}${AWS_S3_BUCKET_PATH_USER_LIBS} /externalworkingdir${AWS_S3_BUCKET_PATH_USER_LIBS}
    echo "Sync complete - user-libs"

    echo "Starting Sync for resources"
    mkdir -p /externalworkingdir${AWS_S3_BUCKET_PATH_RESOURCES}
    aws s3 sync --delete s3://${AWS_S3_BUCKET_NAME}${AWS_S3_BUCKET_PREFIX}${AWS_S3_BUCKET_PATH_RESOURCES} /externalworkingdir${AWS_S3_BUCKET_PATH_RESOURCES}
    echo "Sync complete - resources"

    #final - remove all emtpy folders
    find /externalworkingdir/ -type d -empty -delete

    #recap
    echo "Quick summary:"
    ls -al /externalworkingdir${AWS_S3_BUCKET_PATH_SYSTEM_LIBS_EXTRAS}/
    ls -al /externalworkingdir${AWS_S3_BUCKET_PATH_USER_LIBS}/
    ls -al /externalworkingdir${AWS_S3_BUCKET_PATH_RESOURCES}/
